name: docs
on:
  push:
    branches:
      - documentation

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Configure Git Credentials
        uses: actions/checkout@v4
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com

      - name: Setup Python
        run: |
             sudo apt install -y python3 && pip install mkdocs-material
             echo "cache_id=$(date --utc '+%F')" >> $GITHUB_ENV

      - name: Configure cache
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Deploy to gh-pages
        run: mkdocs gh-deploy

